ministryofjustice/hmpps-locations-inside-prison

- assets/scss/local.scss
- integration_tests/e2e/inactiveCells/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- integration_tests/pages/inactiveCells/index.ts
- server/controllers/inactiveCellsIndex.ts
- server/data/locationsApiClient.test.ts
- server/data/locationsApiClient.ts
- server/middleware/populateBreadcrumbsForLocation.ts
- server/middleware/populateInactiveCells.ts
- server/middleware/populatePrisonId.ts
- server/middleware/populateResidentialSummary.ts
- server/routes/inactiveCellsRouter.ts
- server/routes/index.ts
- server/routes/viewLocationsRouter.ts
- server/services/auditService.ts
- server/services/locationsService.test.ts
- server/services/locationsService.ts
- server/views/pages/inactiveCells/index.njk
> MAP-1177 - Add inactive cells screen

- server/views/pages/inactiveCells/index.njk
- server/views/pages/viewLocations/show.njk
Remove location type from title of inactive cells where local name is present
> Prepend location type to inactive cells where no local name is present

- server/validators/lessThanOrEqualTo.test.ts
- server/validators/lessThanOrEqualTo.ts
Add a test and fix the lessThanOrEqualTo validator
> [MAP-1271] Allow equal values for lessThanOrEqualTo validator

- server/middleware/populateResidentialSummary.ts
- server/views/macros/miniSummary.njk
- server/views/pages/viewLocations/show.njk
This will ensure that screen readers read out the links as specified in the ticket.
[MAP-1275]
[MAP-1275]: https://dsdmoj.atlassian.net/browse/MAP-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1275] Add aria-label attributes to change cell capacity links

- integration_tests/e2e/changeSignedOperationalCapacity/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- integration_tests/pages/changeSignedOperationalCapacity/index.ts
- integration_tests/pages/viewLocations/index.ts
- server/controllers/base/formInitialStep.ts
- server/controllers/changeSignedOperationalCapacity/cancel.ts
- server/controllers/changeSignedOperationalCapacity/index.test.ts
- server/controllers/changeSignedOperationalCapacity/index.ts
- server/controllers/viewLocations/viewLocationsIndex.ts
- server/data/locationsApiClient.ts
- server/lib/permissions.test.ts
- server/lib/permissions.ts
- server/middleware/populateResidentialSummary.ts
- server/routes/changeSignedOperationalCapacity/fields.ts
- server/routes/changeSignedOperationalCapacity/index.ts
- server/routes/changeSignedOperationalCapacity/steps.ts
- server/routes/index.ts
- server/routes/testutils/appSetup.ts
- server/services/locationsService.ts
- server/views/pages/changeSignedOperationalCapacity/index.njk
- server/views/pages/viewLocations/index.njk
- server/views/pages/viewLocations/show.njk
Add change signed operational capacity transaction
MAP-1274
> [MAP-1274] Add change signed operational capacity transaction

- integration_tests/e2e/setCellType/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- integration_tests/pages/page.ts
- integration_tests/pages/setCellType/index.ts
- integration_tests/pages/viewLocations/show.ts
- server/@types/govuk/index.d.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/controllers/base/formInitialStep.ts
- server/controllers/setCellType/cancel.ts
- server/controllers/setCellType/index.test.ts
- server/controllers/setCellType/index.ts
- server/data/baseApiClient.ts
- server/data/locationsApiClient.test.ts
- server/data/locationsApiClient.ts
- server/data/restClient.ts
- server/lib/permissions.test.ts
- server/lib/permissions.ts
- server/middleware/populateResidentialSummary.ts
- server/routes/index.ts
- server/routes/setCellType/fields.ts
- server/routes/setCellType/index.ts
- server/routes/setCellType/steps.ts
- server/services/locationsService.test.ts
- server/services/locationsService.ts
- server/views/pages/setCellType/index.njk
Allow the user to set or change the specific cell type. 
[MAP-1374]
[MAP-1384]
[MAP-1374]: https://dsdmoj.atlassian.net/browse/MAP-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAP-1384]: https://dsdmoj.atlassian.net/browse/MAP-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1374] Set / change specific cell type

- integration_tests/e2e/changeCellCapacity/index.cy.ts
- server/controllers/changeCellCapacity/index.test.ts
- server/controllers/changeCellCapacity/index.ts
- server/routes/changeCellCapacity/fields.ts
- Disable autocomplete for capacity fields
- Validate that working cap as well as max cap is >= occupancy
> Map 1271 feedback

- server/views/pages/changeCellCapacity/change.njk
- server/views/pages/setCellType/change.njk
Make change cell capacity two thirds width
[MAP-1271]
[MAP-1271]: https://dsdmoj.atlassian.net/browse/MAP-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1271] Make change cell capacity two thirds width

- package-lock.json
Upgrade aws clients to fix CVE-2024-41818
> Upgrade aws clients to fix CVE-2024-41818

- integration_tests/e2e/changeCellCapacity/index.cy.ts
- integration_tests/e2e/removeCellType/index.cy.ts
- server/routes/changeCellCapacity/fields.ts
- Add validation for max cap > 0
- Ensure correct precedence of validations
MAP-1453
MAP-1455
> [MAP-1453 , MAP-1455] Validation amendments

- integration_tests/e2e/changeSignedOperationalCapacity/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- server/controllers/changeSignedOperationalCapacity/index.ts
- server/views/pages/changeSignedOperationalCapacity/change.njk
We catch the error and if it is a 404 we just display zero and don't show the "last updated by" line.
MAP-1465
> [MAP-1465] Don't break when signed op cap has never been set

- integration_tests/e2e/removeCellType/index.cy.ts
- integration_tests/e2e/setCellType/index.cy.ts
- server/middleware/populateResidentialSummary.ts
- server/routes/removeCellType/steps.ts
Hide set/change/remove cell type links when cell is inactive
[MAP-1374](https://dsdmoj.atlassian.net/browse/MAP-1374) [MAP-1384](https://dsdmoj.atlassian.net/browse/MAP-1384) [MAP-1388](https://dsdmoj.atlassian.net/browse/MAP-1388)
[MAP-1374]: https://dsdmoj.atlassian.net/browse/MAP-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAP-1384]: https://dsdmoj.atlassian.net/browse/MAP-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAP-1388]: https://dsdmoj.atlassian.net/browse/MAP-1388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cell type amendments

- wiremock/mappings/atrribute-search-noprisoner.json
- wiremock/mappings/atrribute-search-prisoner.json
Only returns prisoners in Brixton
> MAP-1495 Only return prisoner results for Brixton (BXI)

- server/controllers/viewLocations/viewLocationsShow.test.ts
- server/controllers/viewLocations/viewLocationsShow.ts
Don't show convert to non-res action if not leaf (cell) level.
MAP-1461
> MAP-1461: Don't show convert to non-res action if not leaf level

- server/decorators/location.test.ts
- server/decorators/location.ts
- server/middleware/populateResidentialSummary.ts
- server/views/macros/locationsTable.njk
Show non-res cell types in list and on show cell page
[MAP-1555]
[MAP-1555]: https://dsdmoj.atlassian.net/browse/MAP-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-1555: Show non-res cell types in list and on show cell page

- server/controllers/viewLocations/viewLocationsShow.test.ts
- server/controllers/viewLocations/viewLocationsShow.ts
- server/views/pages/nonResidentialConversion/warning.njk
- Do not show convert to non-res action for inactive cells
- Suppress breadcrumb on warning page
- Add padding to warning panel
> Amendements for MAP-1461

- package-lock.json
- package.json
[MAP-1585](https://dsdmoj.atlassian.net/browse/MAP-1585)
[MAP-1585]: https://dsdmoj.atlassian.net/browse/MAP-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-1585 dependency update

- helm_deploy/values-dev.yaml
Olu who is helping us with analytics has a DOM1 laptop and this should allow him to access the service.
MAP-1612
> MAP-1612: Allow DOM1 access to dev

- package-lock.json
- package.json
As MAP developer on alert duties,
I have addressed -CVE-2024-45590
I have done npm audit fix
-> which has addressed same CVE issue
> alert-duties-24.10.01-CVE-2024-45590

- assets/scss/local.scss
- helm_deploy/values-train.yaml
- server/app.ts
- server/config.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/index.njk
- server/views/partials/layout.njk
Unfortunately there's not much I can do in terms of automated testing here, unless we were to have some special integration tests that run as if they were in the training environment, and that's probably not worth the considerable extra effort it would require.
MAP-1630
> MAP-1630: UI changes for training environment

- helm_deploy/values-train.yaml
> fix: Forgot to add the prod URL to training env

- assets/scss/components/_feedback-banner.scss
- server/views/macros/feedbackBanner.njk
> MAP-1631: Make feedback banner bold and 19px as per ACs

- assets/scss/application.scss
- assets/scss/components/_inactive-location-banner.scss
- cypress.config.ts
- integration_tests/e2e/changeTemporaryDeactivationsDetails/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- integration_tests/pages/changeTemporaryDeactivationDetails/details.ts
- integration_tests/pages/inactiveCells/index.ts
- integration_tests/pages/viewLocations/show.ts
- package-lock.json
- server/controllers/changeTemporaryDeactivationDetails/details.test.ts
- server/controllers/changeTemporaryDeactivationDetails/details.ts
- server/controllers/changeTemporaryDeactivationDetails/occupied.test.ts
- server/controllers/changeTemporaryDeactivationDetails/occupied.ts
- server/controllers/deactivateTemporary/details.ts
- server/data/locationsApiClient.ts
- server/data/types/locationsApi/location.d.ts
- server/lib/permissions.test.ts
- server/lib/permissions.ts
- server/routes/changeTemporaryDeactivationDetails/fields.ts
- server/routes/changeTemporaryDeactivationDetails/index.ts
- server/routes/changeTemporaryDeactivationDetails/steps.ts
- server/routes/index.ts
- server/services/locationsService.ts
- server/validators/dateTodayOrInFuture.test.ts
- server/views/macros/inactiveLocationBanner.njk
- server/views/pages/changeTemporaryDeactivationDetails/details.njk
The changes in this PR are related to the [MAP-1292 - Update an inactive cell](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1292) ticket.
> Map 1292 update an inactive cell

- server/utils/azureAppInsights.ts
Add username and Prison ID to the telemetry data, and ignore spammy paths
MAP-1437
> MAP-1437: Improved app insights telemetry

- server/utils/azureAppInsights.ts
> MAP-1437: Second attempt at sending proper App Insights telemetry

- server/routes/changeTemporaryDeactivationDetails/index.ts
- server/routes/deactivateTemporary/index.ts
- server/routes/reactivate/cell/index.ts
| location\_type | count | concat |
| :--- | :--- | :--- |
| ROOM | 187 | 88.6% |
| MEDICAL | 6 | 2.8% |
| GROUP | 5 | 2.4% |
| RESIDENTIAL\_UNIT | 3 | 1.4% |
| ADJUDICATION\_ROOM | 2 | 0.9% |
| MOVEMENT\_AREA | 2 | 0.9% |
| OFFICE | 2 | 0.9% |
| STORE | 1 | 0.5% |
| FAITH\_AREA | 1 | 0.5% |
| HOLDING\_CELL | 1 | 0.5% |
| EXTERNAL\_GROUNDS | 1 | 0.5% |
> MAP-1681 Initial fix for majority of cases which are rooms

- integration_tests/e2e/deactivateTemporary/index.cy.ts
- server/routes/deactivateTemporary/fields.ts
- server/views/pages/deactivateTemporary/details.njk
Changes made in this PR are related to [the following ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1658).
- Updated of related view
- Addition of e2e tests in support of the code changes
> Map 1658 disable browser autofill

- assets/scss/components/_mini-summary.scss
- server/views/pages/changeLocalName/details.njk
- server/views/pages/changeUsedFor/details.njk
- server/views/pages/locationHistory/show.njk
- server/views/pages/removeLocalName/details.njk
- server/views/pages/setLocalName/details.njk
- server/views/pages/viewLocations/show.njk
Changes made within this PR cover the requirements of [MAP-1680](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=625e8c18fd06270069bf7ddd&selectedIssue=MAP-1680).
- Removal of additional div elements
- Update to SCSS to fix text link margin on smaller screens
[MAP-1680]: https://dsdmoj.atlassian.net/browse/MAP-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Map 1680 fix incorrect layouts

- server/views/pages/nonResidentialConversion/details.njk
- server/views/pages/nonResidentialConversion/occupied.njk
> MAP-1680 Additional fixes

- integration_tests/e2e/changeCellCapacity/index.cy.ts
- integration_tests/e2e/nonResidentialConversion/index.cy.ts
- integration_tests/e2e/removeCellType/index.cy.ts
- integration_tests/e2e/setCellType/index.cy.ts
- integration_tests/e2e/viewLocations/show.cy.ts
- server/views/pages/viewLocations/show.njk
Changes made in this PR are related to [MAP-1677](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=625e8c18fd06270069bf7ddd&selectedIssue=MAP-1677)
Updates include:
- Updated view elements to display the correct button
- Updated tests to cater for the changes made
[MAP-1677]: https://dsdmoj.atlassian.net/browse/MAP-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Map 1677 update deactivate location type buttons

- server/views/pages/deactivate/permanent/details.njk
- server/views/pages/deactivate/temporary/details.njk
- server/views/pages/deactivate/type.njk
> MAP-1655: Make all deactivate titles two thirds width

- server/@types/express/index.d.ts
- server/controllers/changeLocalName/details.test.ts
- server/controllers/changeLocalName/details.ts
- server/controllers/changeNonResidentialType/details.test.ts
- server/controllers/changeNonResidentialType/details.ts
- server/controllers/changeTemporaryDeactivationDetails/details.test.ts
- server/controllers/changeTemporaryDeactivationDetails/details.ts
- server/controllers/reactivate/cells/confirm.test.ts
- server/controllers/reactivate/cells/confirm.ts
- server/controllers/removeLocalName/check.test.ts
- server/controllers/removeLocalName/check.ts
- server/controllers/setLocalName/details.test.ts
- server/controllers/setLocalName/details.ts
> MAP-1689: Add more GA events

- assets/scss/local.scss
[MAP-1695](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-1695)
[MAP-1695]: https://dsdmoj.atlassian.net/browse/MAP-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-1965 changed css to remove empty space in home page

- server/controllers/changeNonResidentialType/details.test.ts
- server/controllers/changeNonResidentialType/details.ts
Fix where validation error clears selection of "Other" type when description is not entered and save is attempted for non-residential room.
> MAP-1770: Fixing non-res room type error

- integration_tests/e2e/viewLocations/show.cy.ts
- server/views/macros/inactiveLocationBanner.njk
Show "Not provided" for missing deactivation details.
MAP-1741
> MAP-1741: Show "Not provided" for missing deactivation details

- server/controllers/deactivate/permanent/confirm.test.ts
- server/controllers/deactivate/permanent/confirm.ts
- server/controllers/deactivate/temporary/confirm.test.ts
- server/controllers/deactivate/temporary/confirm.ts
- server/controllers/nonResidentialConversion/confirm.test.ts
- server/controllers/nonResidentialConversion/confirm.ts
- server/decorators/location.ts
- server/errorHandler.test.ts
- server/errorHandler.ts
Send handled API errors and any other unhandled errors to Google Analytics.
MAP-1730
> MAP-1730: Send Google Analytics event for unhandled error

- assets/js/buttonMenu.js
- integration_tests/support/index.ts
- package-lock.json
- package.json
- server/views/pages/viewLocations/show.njk
Updated @ministryofjustice/frontend to 3.0.2 and ensured that the button menu is working as expected.
> MAP-1774 - Update MOJ/frontend

- .husky/pre-commit
- package.json
> MAP-1765: Migrate Husky to remove v9 deprecation warning

- integration_tests/e2e/deactivate/permanent.cy.ts
- server/controllers/archivedLocationsIndex.ts
- server/controllers/deactivate/permanent/confirm.test.ts
- server/controllers/deactivate/permanent/confirm.ts
- server/views/pages/archivedLocations/index.njk
It has been changed the landing page to archived locations and it has been needed integration test to reflect this change.
> MAP-1768 Permanent deactivation routing to location overview instead of archived locations

- integration_tests/e2e/inactiveCells/index.cy.ts
- integration_tests/pages/inactiveCells/index.ts
- server/views/pages/inactiveCells/index.njk
No inactive cells page variant required for lists of inactive cells 
Table is empty so need to present only this Message 'There are no inactive cells'
> MAP-1788 No inactive cells page variant required for lists of inactive cells 

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- package-lock.json
- package.json
This PR is only to update node to v22. Because of this, 
[See PR in template project that also updates to node 22]
(https://github.com/ministryofjustice/hmpps-template-typescript/pull/474/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47)
> MAP-1941 node 22 as per Template

- .circleci/config.yml
- .gitignore
- README.md
- package-lock.json
- package.json
- tsconfig.json
As part of MAP-1596 we have initiated an activity to be able to check report in the Continuous Integration tool CI and It is set up a treshold configuration which can be modified as per requirement.
> MAP-2028 jest coverage report circle CI and treshold default config

- server/controllers/locationHistoryShow.ts
- server/data/types/locationsApi/location.d.ts
- server/data/types/locationsApi/locationForLocalName.d.ts
- server/services/feComponentsService.ts
- server/testutils/factories/location.ts
- server/utils/renderMacro.ts
> MAP-2060: Support array values in history

- server/errorHandler.test.ts
- server/errorHandler.ts
- server/views/pages/errors/404.njk
- server/views/pages/errors/generic.njk
> MAP-2115: Add 404 error page

- server/routes/changeSignedOperationalCapacity/fields.ts
Changed 'ben' to 'been' in the declaration.
> Update field.ts to fix typo

- server/routes/dpr/index.ts
- server/views/pages/managementReporting/index.njk
- server/views/partials/dprLayout.njk
The Pull Request introduces changes to incorporate breadcrumb functionality into the Management Reporting feature, improving navigation consistency across pages.
- Code Updates in Backend:
- Added the addBreadcrumb middleware to support breadcrumb navigation in relevant routes within index.ts.
- Updated /management-reporting route to dynamically generate breadcrumb links.
- Template Adjustments:
- Removed unused breadcrumb imports from index.njk and dprLayout.njk views. This cleanup avoids redundant code usage in the frontend templates.
These changes primarily enhance user navigation while removing unnecessary components for streamlined templates.
> MAP-2409 Add breadcrumb middleware for reports navigation

- assets/js/autoFillNumbering.js
- assets/js/index.js
- integration_tests/e2e/createLocation/landing/createCells/capacities.cy.ts
- integration_tests/e2e/createLocation/landing/createCells/cellNumbers.cy.ts
- integration_tests/e2e/createLocation/landing/createCells/doorNumbers.cy.ts
- integration_tests/e2e/createLocation/landing/createCells/goToCreateCellsCapacitiesPage.ts
- integration_tests/pages/commonTransactions/createCells/bulk-sanitation.ts
- integration_tests/pages/commonTransactions/createCells/capacities.ts
- integration_tests/pages/commonTransactions/createCells/details.ts
- integration_tests/pages/commonTransactions/createCells/usedFor.ts
- integration_tests/pages/page.ts
- server/@types/express/index.d.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/commonTransactions/createCells/capacities.ts
- server/commonTransactions/createCells/cellDoorNumbers.ts
- server/commonTransactions/createCells/fields.ts
- server/commonTransactions/createCells/getCellPath.ts
- server/commonTransactions/createCells/steps.ts
- server/controllers/base/formInitialStep.ts
- server/views/commonTransactions/createCells/capacities.njk
- server/views/partials/formStep.njk
> MAP-2524: Add create cells capacities screen

- integration_tests/e2e/createLocation/landing/createCells/goToCreateCellsWithoutSanitationPage.ts
- integration_tests/e2e/createLocation/landing/createCells/withoutSanitation.cy.ts
- integration_tests/pages/commonTransactions/createCells/withoutSanitation.ts
- server/commonTransactions/createCells/cellNumbers.ts
- server/commonTransactions/createCells/fields.ts
- server/commonTransactions/createCells/steps.ts
- server/commonTransactions/createCells/withoutSanitation.ts
- server/views/partials/formStep.njk
> MAP-2556: Add without sanitation screen in create cells

- integration_tests/e2e/createLocation/landing/createCells/goToCreateCellsBulkSanitationPage.ts
- integration_tests/e2e/createLocation/landing/createCells/usedFor.cy.ts
- integration_tests/e2e/createLocation/landing/createCells/withoutSanitation.cy.ts
- integration_tests/pages/commonTransactions/createCells/usedFor.ts
- server/commonTransactions/createCells/fields.ts
- server/commonTransactions/createCells/steps.ts
- server/commonTransactions/createCells/usedFor.ts
- server/views/commonTransactions/createCells/usedFor.njk
- server/views/commonTransactions/createCells/withoutSanitation.njk
> MAP-2672: Add used for screen in create cells

- integration_tests/e2e/deleteDraftLocation/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- integration_tests/pages/deleteDraftLocation/confirm.ts
- integration_tests/pages/viewLocations/show.ts
- server/@types/express/index.d.ts
- server/controllers/deleteDraftLocation/confirm.test.ts
- server/controllers/deleteDraftLocation/confirm.ts
- server/controllers/viewLocations/viewLocationsShow.test.ts
- server/controllers/viewLocations/viewLocationsShow.ts
- server/data/locationsApiClient.ts
- server/middleware/addAction.ts
- server/routes/deleteDraftLocation/index.ts
- server/routes/deleteDraftLocation/steps.ts
- server/routes/index.ts
- server/routes/viewLocationsRouter.ts
- server/services/locationsService.ts
- server/views/pages/deleteDraftLocation/confirm.njk
- server/views/pages/viewLocations/show.njk
This PR relates to [MAP-2648](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-2648)
[MAP-2648]: https://dsdmoj.atlassian.net/browse/MAP-2648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-2648: delete draft parent location

- integration_tests/e2e/deleteDraftLocation/index.cy.ts
- integration_tests/pages/deleteDraftLocation/confirm.ts
- server/@types/express/index.d.ts
- server/controllers/deleteDraftLocation/confirm.ts
- server/views/pages/deleteDraftLocation/confirm.njk
> MAP-2649: add delete draft cell text & update deleteDraftLocation tests

- integration_tests/e2e/admin/index.cy.ts
- integration_tests/mockApis/locationsApi.ts
- integration_tests/pages/admin/index.ts
- integration_tests/pages/admin/segInRollCount/confirm.ts
- server/controllers/admin/segInRollCount/confirm.test.ts
- server/controllers/admin/segInRollCount/confirm.ts
- server/data/locationsApiClient.test.ts
- server/data/locationsApiClient.ts
- server/routes/admin/segInRollCount/fields.ts
- server/routes/admin/segInRollCount/index.ts
- server/routes/admin/segInRollCount/steps.ts
- server/routes/adminRouter.test.ts
- server/routes/index.ts
- server/services/locationsService.test.ts
- server/services/locationsService.ts
- server/views/pages/admin/index.njk
- server/views/pages/admin/segInRollCount/confirm.njk
> MAP-2783: add functionality to update seg in roll count
