ministryofjustice/hmpps-locations-inside-prison

package-lock.json, package.json
Focusing on typescript and govuk-frontend to get rid of the alerts we get daily
=> MAP-1379 update NPM dependencies

server/controllers/changeCellCapacity/index.test.ts, server/controllers/changeCellCapacity/index.ts
This seems to happen when the cell is inactive, causing an error for the user
[MAP-1271]
[MAP-1271]: https://dsdmoj.atlassian.net/browse/MAP-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAP-1271] Don't crash when prisoner locations are not returned

server/controllers/changeCellCapacity/confirm.ts
This makes sure that the update has been processed by the time we redirect back to the view cell page.
[MAP-1271]
[MAP-1271]: https://dsdmoj.atlassian.net/browse/MAP-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAP-1271] Await cell capacity change

integration_tests/e2e/changeCellCapacity/index.cy.ts, server/controllers/changeCellCapacity/cancel.ts, server/controllers/changeCellCapacity/confirm.test.ts, server/controllers/changeCellCapacity/confirm.ts, server/controllers/changeCellCapacity/index.test.ts, server/controllers/changeCellCapacity/index.ts, server/controllers/setCellType/cancel.ts, server/controllers/setCellType/index.test.ts, server/controllers/setCellType/index.ts, server/routes/changeCellCapacity/steps.ts, server/routes/setCellType/steps.ts, server/views/pages/changeCellCapacity/change.njk, server/views/pages/setCellType/change.njk
We have removed the /cancel endpoints and instead we reset when the user visits / and immediately redirect to /change. If we are linking back and don't want to reset then we just link straight to /change.
See: https://github.com/ministryofjustice/hmpps-locations-inside-prison/pull/61
=> Change back links to follow new pattern

package-lock.json, package.json, server/app.ts
This should stop it crashing when API calls fail
MAP-1474
=> [MAP-1474] Use express-async-errors

server/views/pages/error.njk
Some of the text was spilling out of the page grid layout, and the status code was displaying above the title.
MAP-1474
=> [MAP-1474] Rework the styling of the error page a bit

server/routes/viewLocationsRouter.ts
Related to the following ticket: [MAP-1400](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1400)
Changes made in this PR:
- Add missing breadcrumb
Supporting screenshots:
[MAP-1400]: https://dsdmoj.atlassian.net/browse/MAP-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1400 - Add missing Residential locations breadcrumb

server/middleware/setUpWebSecurity.ts
There was an error in the browser console saying that it was blocking the frontend components from loading fonts.
=> Allow HMPPS frontend components to load fonts

helm_deploy/hmpps-locations-inside-prison/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-train.yaml
We need prisons to have access because some MoJ laptops show up as being in this IP range, including a performance analyst who is helping us.
We need Cloud Platforms to have access so that the Dev Portal can keep track of drift.
The other IP group will allow the rest of us access.
The `internal` group has been removed because it is deprecated.
MAP-1660
=> MAP-1660: Allow access to all environments for three IP ranges

server/views/pages/index.njk, server/views/partials/layout.njk
=> MAP-1630: Get rid of gap above training header at some screen widths

server/controllers/cellConversion/confirm.test.ts, server/controllers/cellConversion/confirm.ts, server/controllers/changeCellCapacity/confirm.test.ts, server/controllers/changeCellCapacity/confirm.ts, server/controllers/changeSignedOperationalCapacity/index.test.ts, server/controllers/changeSignedOperationalCapacity/index.ts, server/controllers/changeUsedFor/details.test.ts, server/controllers/changeUsedFor/details.ts, server/controllers/deactivateTemporary/confirm.test.ts, server/controllers/deactivateTemporary/confirm.ts, server/controllers/nonResidentialConversion/confirm.test.ts, server/controllers/nonResidentialConversion/confirm.ts, server/controllers/reactivate/cell/confirm.test.ts, server/controllers/reactivate/cell/confirm.ts, server/controllers/removeCellType/confirm.test.ts, server/controllers/removeCellType/confirm.ts, server/controllers/setCellType/index.test.ts, server/controllers/setCellType/index.ts, server/services/analyticsService.test.ts, server/services/analyticsService.ts
Send an event to Google Analytics via the measurement protocol when a transaction is completed.
Some of the controllers were missing tests for `saveValues` so I've added them where necessary.
MAP-1661
=> MAP-1661: Send GA events when completing transaction

server/middleware/setUpWebSecurity.ts
I am still getting occasional errors in the broser console about content security policy violations. This will hopefully fix it.
=> Add MoJ shared component styles to content security policy

server/controllers/removeCellType/remove.test.ts, server/controllers/removeCellType/remove.ts
Depending on working cap etc. the final page of the remove cell type journey could be either `/confirm` or `/remove`. This makes sure the GA event still gets sent if they go via the `/remove` page.
MAP-1661
=> MAP-1661: Send GA event for remove cell type secondary form route

server/controllers/changeTemporaryDeactivationDetails/details.test.ts, server/controllers/changeTemporaryDeactivationDetails/details.ts
- Updates compareInitialAndSubmittedValues() to handle undefined values in the initial data when comparing to the submitted empty string data. This only occurs when the date fields are initially empty and 'undefined' is returns from the API. 
- Added supporting unit test
=> MAP-1292 - Add fix for edge case when date values are undefined

server/services/locationsService.test.ts, server/services/locationsService.ts
We thought that the service was spawned once pre request, but it is actually a long-lived object so this code would cause the constant values to be kept in memory until pod restart, so any new values would never be retrieved. Instead we will remove this code and let Redis handle the caching.
MAP-1489
=> MAP-1489: Remove indefinite caching in locations service

integration_tests/e2e/inactiveCells/index.cy.ts, server/views/pages/inactiveCells/index.njk
The changes made in this PR cover the requirements detailed within [MAP-1679](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1679).
- Updated view to display reason description data when it is available
- Added supporting e2e tests
**Screenshot**
[MAP-1679]: https://dsdmoj.atlassian.net/browse/MAP-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Map 1679 add reason description to inactive cell list

integration_tests/e2e/changeNonResidentialRoomType/index.cy.ts, server/controllers/changeNonResidentialType/details.test.ts, server/controllers/changeNonResidentialType/details.ts
non-residential room, updating then saving the description text in the "Other" field on the "Change Room Type" need to display a Success message.
=> Map-1698 [Resi locations] Success message missing when updating "Other" description in non-residential room details

server/views/partials/layout.njk
I'm not sure if this will work or not but currently tag manager is having some issues due to COEP policy.
MAP-1732
=> MAP-1732: Add crossorigin attribute to GTM script

integration_tests/e2e/deactivate/permanent.cy.ts, server/controllers/deactivate/type.ts
- Show correct validation error when not selecting deactivation type
- Remember deactivation type when clicking back
MAP-1655
=> MAP-1655: Permanent deactivate - amendments

assets/scss/components/_sticky-footer.scss, server/views/partials/layout.njk
[Previous PR](https://github.com/ministryofjustice/hmpps-locations-inside-prison/pull/175) fixed the footer issue in training mode but left a bug in non-training (the blue bar was positioned too high)
This code change is a fix for that and position of blue bar is at the bottom of view in non-training mode
non-training view
training view
=> MAP-1700 fixed sticky footer so tight to bottom in non-training view

integration_tests/e2e/setCellType/index.cy.ts, server/controllers/setCellType/index.test.ts, server/controllers/setCellType/index.ts, server/data/types/locationsApi/location.d.ts
- Make sure boxes are checked if cell types already exist
- Don't show success banner if nothing has changed
These were both regressions caused by changing the middleware so that it decorates the location. Unfortunately this slipped through holes in my earlier test coverage so I have added more tests to prevent further regressions.
MAP-1697
=> MAP-1697: Make sure that the fields are pre-populated for change cell type

server/controllers/base/formInitialStep.ts, server/helpers/field/validateDateInput.test.ts, server/helpers/field/validateDateInput.ts, server/validators/dateTodayOrInFuture.test.ts, server/validators/dateTodayOrInFuture.ts
[MAP-1740](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-1740)
Date input should not accept really old dates
Date input should accept today onwards
Date input Year must be at least 4 numbers long (added new validation message for this)
[MAP-1740]: https://dsdmoj.atlassian.net/browse/MAP-1740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1740 fixed date bugs

integration_tests/support/index.ts, server/lib/permissions.test.ts, server/lib/permissions.ts
People without the op cap role should still be able to temp deactivate and edit deactivation details
MAP-1655
=> MAP-1655: Update permissions

integration_tests/e2e/archivedLocations/index.cy.ts, integration_tests/pages/archivedLocations/index.ts, server/views/pages/archivedLocations/index.njk
Update Archived locations screen to display the ‘Reason’ value.
the table that lists all permanently inactive flagged locations in the establishment 
with the addition of a column heading ‘Reason’
and the new column ‘Reason’ displays the permanent deactivation/archive reason ID
and if the reason does not exist display the content ‘Not provided’ 
and reason column will appear after ‘Location type’ and before ‘Deactivated by’
=> MAP-1694 Update Archived locations page to display ‘Reason’

server/controllers/changeNonResidentialType/details.ts
When submitting null, it was being validated correctly, but was pre-populating the stored value, rather than null. 
It now pre-populates as null.
=> MAP-1785: Fixing non-res 'other' field validation bug

assets/scss/local.scss, server/views/macros/locationsTable.njk
[ MAP-1773](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-1773)
The contents of the location column in the table should be vertically  middle aligned
Now looks like this:
=> MAP-1773 added css to middle-align the location column of the table

assets/js/mojFrontendInit.js, integration_tests/e2e/reactivate/cells/index.cy.ts, server/routes/changeTemporaryDeactivationDetails/fields.ts, server/routes/removeLocalName/fields.ts, server/views/pages/inactiveCells/index.njk
Disable autocomplete on various fields. This also fixes the back button issue.
MAP-1772
=> Clear inactive cells checkboxes after browser back button

README.md, integration_tests/e2e/changeUsedFor/index.cy.ts, server/controllers/changeUsedFor/details.test.ts, server/controllers/changeUsedFor/details.ts, server/middleware/populateResidentialSummary.ts, server/views/pages/changeUsedFor/details.njk
- [MAP-1960](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=6419ad1b67102fc717c0d25e&selectedIssue=MAP-1960): Allows user, at residential cell level, to make changes to the used for when making making changes to a location.
- Small update to readme for running int-ui tests 
[MAP-1960]: https://dsdmoj.atlassian.net/browse/MAP-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Map 1960: Adding change used for link on a cell level
